### PR TITLE
Add charge_now and statistics URL

### PR DESCRIPTION
**Pull request by robthebold**
Added a function to send "charge_now" command to car that has been set for delayed charging. See https://github.com/edent/BMW-i-Remote#initiate-charging
Added URL for the vehicle_statistics. re: https://github.com/edent/BMW-i-Remote#get-all-trip-details
Added additional ExecutionState values (NOT_EXECUTED, TIMED_OUT) see https://github.com/edent/BMW-i-Remote#values-7

### CODE REVIEW

**Comment by robthebold** [comment]
I think only added URLs in const.py need to go into master, no other changes from my branch since those are out of date on my end

**Comment by rikroe** [comment]
Cool, thanks!

If only the changes in const.py are needed, could you maybe create a second branch and just do the changes there (resulting in a new PR)?
Or save your changes locally, then revert all changes to bimmerconnected master, apply the changes for charge_now and statistics and force-push to your repo again (no new PR)?

Little bit of effort but makes it much clearer to understand what relevant changes we have :)

**Comment by robthebold** [comment]
Sorry, I wasn't really clear there. I meant that only the changes in const.py had any conflicts that needed to be resolved. The rest of the changes merge without manual resolution. I'll look at branching.

**Comment by rikroe** [comment]
I see, however there are also changes from other PRs in your code (e.g. SendPOI) which should come from the respective PRs and not from this one...

**Comment by robthebold** [comment]
> This contains some old commits indeed.
> I have merged some PRs in the meanwhile. Can you rebase and update the PR?

Yes, working on this.

**Pull request closed without merging**
