### PR TITLE
Fix login issues in China

### LINKED ISSUE #220: 0.7.8 did not fix login issue for "china".
0.7.8 did not fix login issue for "china".
HA 0.117.1 did not fix.

_Originally posted by @nichwang88 in https://github.com/bimmerconnected/bimmer_connected/issues/208#issuecomment-719906177_

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

The changes in 0.7.8 lead to users in China (and probably North America) not being able to login anymore.
Apparently China uses older credentials than rest_of_world. However with the old credentials and the new API, at least china and rest_of_world are working (north_america should be working as well).

## Type of change
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #220 
- This PR is related to issue: #208 

## Checklist

- [X] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Review by gerard33 — APPROVED** [review]
@robthebold Are you able to test this version so we have confirmation this works for US as well?

**Comment by robthebold** [comment]
> @robthebold Are you able to test this version so we have confirmation this works for US as well?

Lemme check it out. All necessary changes are merged in the main project branch, right?

**Comment by rikroe** [comment]
Yep - I just created an empty NA account to test if I am able to log in and at least that works. Now the question is only if you get your car's data. 
Just download `bimmer_connected==0.7.10` from PyPI and check the status ;)

**Comment by robthebold** [comment]
:(
Checked with up-to-date code, and bimmer bummer, can't get authorized in region north_america.

I tried 

`python3 cli.py status <username> <password>`

and got following error returned:

`UNAUTHORIZED (received status code 401 and expected 200.)
`

if, OTOH, I try:

`python3 cli.py status <username> <wrong_password>`

I get:

`UNKNOWN_ERROR (received status code 400 and expected 200.)`

**Comment by rikroe** [comment]
Oh gosh this is making me mad. 

I am 100% sure it was working with exactly this code.... I'll have a look

**Comment by rikroe** [comment]
Hey @robthebold, could you please try changing this line
https://github.com/bimmerconnected/bimmer_connected/blob/b830a90b0aaccc6efafeac29b72be61e3b9867dd/bimmer_connected/country_selector.py#L25
To `b2vapi.bmwgroup.us/gcdm`?

I was sure to have tested the new URL but maybe I was using the wrong branch...

**Comment by robthebold** [comment]
That works.

**Pull request merged**
