### PR TITLE
Fix key-error when response returns no json

### PR DESCRIPTION
**Pull request by EddyK69**
## Proposed change

When certain service if not available (RangeMap for example), the response.json() does not contain the service-key. 
This PR fixes the unhandled exception and prevents stopping service-loop.

## Type of change
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Additional information

Also extended the data_anonymizer :D

## Checklist

- [X] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by rikroe** [comment]
Many thanks for this, will definetly include the extended anonymizer!
Regarding failed services, I'd like your opinion on #213 (I am trying to fix the source of the issue there).

**Comment by EddyK69** [comment]
> Regarding failed services, I'd like your opinion on #213 (I am trying to fix the source of the issue there).

I will look at this, but, my car supports RangeMaps but the request returns 500 most of the times, sometimes 200. So, my fix wil handle those request returning no valid key in the request.json(). This has nothing to do with the car support a service or not...

**Comment by rikroe** [comment]
Ah, that is good to know! Then it is for sure better to also account for this!

**Comment by EddyK69** [comment]
> Regarding failed services, I'd like your opinion on #213 (I am trying to fix the source of the issue there).

@rikroe PR #213 seems good to me! No issues found...

**Comment by rikroe** [comment]
Thanks! Regarding `RANGE_POLYGON`/`RANGE_CIRCLE`: Do you sometimes get a valid response? 
If not it might make sense to adjust the code  of #213 as `RANGE_POLGYON` seems to have different requirements (app security? additional passwords?) than `RANGE_CIRCLE` so we can better control when to use which data.

**Review by rikroe — APPROVED** [review]

**Comment by EddyK69** [comment]
I tried to get a valid response the last few days, but i only get 500’s, not a single 200 unfortunately. I agree on adding the #213 to resolve this, although my Rangemap != UNSUPPORTED

**Pull request merged**
