### PR TITLE
Migrate to vehicles v2 API

### PR DESCRIPTION
**Pull request by rikroe**
## Breaking change
- `vehicle.doors_and_windows.convertible_top` has been removed as we don't know how it is represented in the new API. It could be part of `vehicle.doors_and_windows.lids` if located similarly to the sunroof.

## Proposed change

Using the demo vehicles feature in the MyBMW app I was able to piece together most of the changes for `v2` of the vehicles API (currently used by MyBMW).

The hope is that this also solves the HTTP 429 issue we get from the old vehicles API.

There are some things missing/some tests failing due to missing data:
- [ ] `vehicle.doors_and_windows.convertible_top` missing
- [x] everything related to charging time, i.e. when will the vehicle start/finish charging

Once #458 is merged and released, I'll mark some people who provided fingerprints before in this PR to get some additional data for these specific cases.

## Type of change
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by nilsvdb82** [comment]
Fingerprint X5 45e, connected to charger, not charging (fully charged a few minutes ago)

[state_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8958204/state_bmw_0.txt)
[vehicles_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8958205/vehicles_bmw_0.txt)
[vehicles_bmw_1.txt](https://github.com/bimmerconnected/bimmer_connected/files/8958206/vehicles_bmw_1.txt)
[WBATA000000C00000_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8958207/WBATA000000C00000_bmw_0.txt)

**Comment by rikroe** [comment]
Thanks all! Unfortunately, not the one we're needing: Basically, we need a fingerprint when the BMW app either displays "start charging at ..." or "finished charging at ..." (don't know how it is actually called, but you know what I mean).

@havrla argh this stupid 429 error... If possible, try the following: from `cli.py`, delete or comment out the whole line [136](https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/cli.py#L136) (`await account.get_vehicles()`). The error shouldn't occur anymore in this case.

**Comment by jav4** [comment]
Here you have now. It's currently charging...

[state_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8959098/state_bmw_0.txt)
[vehicles_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8959099/vehicles_bmw_0.txt)
[vehicles_bmw_1.txt](https://github.com/bimmerconnected/bimmer_connected/files/8959101/vehicles_bmw_1.txt)
[vehicles_mini_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8959103/vehicles_mini_0.txt)
[WBA0P000X0FL00000_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/8959104/WBA0P000X0FL00000_bmw_0.txt)

**Comment by rikroe** [comment]
Thanks guys, you're awesome!

I'll follow up on some other test related issue (but the main thing is done) and waiting for @skrashevich regarding the convertible top!

**Comment by rikroe** [comment]
As this seems to mitigate the 429 issues, I'd rather have this merged & published soon.
The missing `convertibleTop` sensor can be added again afterwards.

**Review by gerard33 — DISMISSED** [review]

**Review by gerard33 — APPROVED** [review]

**Pull request merged**
