### PR TITLE
added "last_trip" to vehicle attributes

### PR DESCRIPTION
**Pull request by m1n3rva**
Goal: get the information about the last trip from the server.

See also: https://github.com/edent/BMW-i-Remote#get-last-trip

### CODE REVIEW

**Comment by m1n3rva** [comment]
notes to myself: 
1. Wating for feedback in #64 
1. Needs some rebasing as there were some changes on master in the mean time.
1. Before merging, create a **second** F45 vehicle, because we already have another F45 in our test database.

**Comment by mzjkt** [comment]
I get the information about the last trip and all trip from the server.
my vehicle is BMW X1 25Le.
It's almost the same system as 225xe.
[2018-10-18_17-47-18.zip](https://github.com/m1n3rva/bimmer_connected/files/2491340/2018-10-18_17-47-18.zip)

**Comment by m1n3rva** [comment]
@mzjkt Thx for the data 😄 I'll see, how we could parse that...

**Comment by slideup-benni** [comment]
Is there any progess? :)
do you need additional data?
i could test with a 225xe

**Comment by gerard33** [comment]
@slideup-benni Would be great if you could test it with your car. If all looks well I can merge this PR.

**Pull request closed without merging**
