### PR TITLE
Added new classes for statistic, destinations, rangemaps and trip services

### PR DESCRIPTION
**Pull request by Markinus**
This is a different suggestion implementation of the sub services to https://github.com/bimmerconnected/bimmer_connected/pull/137.
The data updating is in one place and all services are handled in own classes and files. The user is able to read all values directly with methods. In this first step the subclasses and implementations only.
What do you think about it?

### CODE REVIEW

**Comment by Markinus** [comment]
@rikroe,  in the first step the code ist done. It would be great if you could review it whether this extension is ok for you or not. If yes then I would add some tests and finish it.

**Comment by rikroe** [comment]
Nicely done, many thanks! Thats a lot of work!

Cannot promise you to fully review your changes within the next week, unfortunately. But looking forward to it!

**Comment by Markinus** [comment]
The next 2 weeks I'm not available too, so it's not a problem.

**Comment by Markinus** [comment]
Hi @rikroe,
could you check this PR?

**Comment by rikroe** [comment]
This looks very good! Unfortunately I cannot test most of the functions (my car is too old)...
Therefore I am really dependent on tests and can only approve your changes with a peaceful mind if there are tests for these as well (so one dummy car that has all the settings etc.).
With that done, I am happy to approve this!

And one remark: It's `deprecated` instead of `depreceted` in `state.py` ;) Maybe we could also throw warnings instead of info.
But really like that you keep it backwards-compatible!

Many thanks for your work!

**Comment by Rantaki** [comment]
Really looking forward getting the statistics of the trips! Does this PR cover the possibility to start immediate charging?

No idea what is needed to get this work through Home Assistant but hopefully it can be done. I was looking for a way to start the charging but I've been also wondering why original BMW app does not provide the trip statistics.

**Comment by Markinus** [comment]
Hi @rikroe,
ok, I will finish this PR and extend the tests.

**Comment by Markinus** [comment]
Hi @rikroe,

I just added some tests. It would be great if you could check it. What do you think?

**Comment by rikroe** [comment]
Very nice work! I think it is almost ready to be merged!
The _coverall_ check is now failing because quite some parts of `state.py` are not tested - especially the ones that throw a `deprecation` warning:
https://coveralls.io/builds/33587743/source?filename=bimmer_connected%2Fstate.py

I think it would be great to have the old `state` calls/attributes in there as well, throwing a warning but actually returning the correct value (so it is as well checked that we're compatible to previous versions).

Also, it might be a good test to use a vehicle that doesn't have all the information so we don't get any unexpected behavior (now or some time in the future).

Many thanks!

**Comment by Markinus** [comment]
@rikroe, I restored the tests for the depreced functions. Now all tests have passed successfuly.
I tested it already with different data (from my G30 PHEV where some stuff is missing). I will add the G30_PHEV data in the future to this repo but I would suggest to do it maybe in a second step. Ok for you?

**Review by rikroe — APPROVED** [review]
LGTM.
@gerard33 you want to have a look as well? Otherwise I'll merge this within the next couple of days.

**Review by rikroe — CHANGES_REQUESTED** [review]
Sorry to first approve and then request something new...

Don't know why it is not clear to see in GitHub, but the `flake` and `pylint` tests are failing:
https://travis-ci.org/github/bimmerconnected/bimmer_connected

Could you please have a look at that as well?

@gerard33 Do you know why travis is not included in the PR tests anymore?

**Comment by Markinus** [comment]
@rikroe, done. Now are all tests "green"

**Review by rikroe — APPROVED** [review]

**Comment by Markinus** [comment]
@rikroe, I've prepared the testdata of the G30 and two further lagacy services (e.g. for soc info). I will create a new PR if this is merged.

**Comment by gerard33** [comment]
Impressive PR, thanks for your work 👍

Had a quick look and this will impact the Home Assistant integration though. The changes from `state.py` to `vehicle_status.py` will give the users a lot of warnings in the logs.

For example this code https://github.com/home-assistant/core/blob/dev/homeassistant/components/bmw_connected_drive/binary_sensor.py#L168 will trigger this warning which is visible in the HA log -> `_LOGGER.warning("Funcion deprecated use state.vehicle_status.all_lids_closed instead")`

So let's first agree on how to approach with that (change it in the HA integration or in this library) before bumping the library in HA.
And let's also discuss how the new data that is made available can be used in HA. Is this data only available for electric cars and PHEVs?

@Markinus I will invite you to the bimmerconnected team so we can discuss this further there.

**Comment by Markinus** [comment]
Hi,
I don't know whether all cars are supporting it or only PHEV/EVs (but some values are definitly PHEV/EV only).  It seems to be depending on the cars OS version, too. (OS6 and OS7 on a G30 are different). I'm not using HA, I'm doing it for a connection to openhab. I cannot say what the best way for HA is.

**Comment by netdata-be** [comment]
This PR only works correctly for iDrive7
I have a BMW X1 Hybrid and the code fails because of missing attributes in the responses.
For example iDrive6 does not have support for range maps.

**Comment by Markinus** [comment]
My OS7 Hybrid is not supporting it too... what du you mean with 'code fail'? ...

**Comment by EddyK69** [comment]
Hi all. I’m looking forward to these new services..Specially the lasttrip function to make automic trip logs in HA. I have a BMW i3; if i can support you with its json exports, please let me know!

**Comment by EddyK69** [comment]
@gerard33 When do you expect these new services are available in a new version?

**Comment by gerard33** [comment]
We do need some input and inspiration for this. Both @rikroe and I don't have an electric/hybrid vehicle, so if you can share the fingerprint and screenprints of the relevant parts of the BMW app, we can see how to use this in HA.

**Comment by EddyK69** [comment]
@rikroe & @gerard33 : i will provide the fingerprints of my i3 asap via pm asap...

**Comment by nilsvdb82** [comment]
Please know that BMW car updates can enable extra features on iDrive7, which translate in extra/missing attributes or fingerprint data, even tough it's the same car. 
I will provide a new fingerprint for my X5 45e after I receive the latest (big) update, and then we can verify this using pre/post fingerprint data.

**Comment by EddyK69** [comment]
> @rikroe & @gerard33 : i will provide the fingerprints of my i3 asap...

@gerard33 @rikroe How can I pm you to provide the fingerprint-files?

**Comment by gerard33** [comment]
You can add your fingerprint files as attachments here. The script removes all privacy information like VIN and lat,lon.

If you feel more comfortable sending them in a pm, you can pm them to me on the HA forum.

**Comment by EddyK69** [comment]
@gerard33 Here my fingerprint files....
[bmw_i3.zip](https://github.com/bimmerconnected/bimmer_connected/files/5464872/bmw_i3.zip)

**Comment by EddyK69** [comment]
Regarding integration of these new services in HA: i made some progress already.
Sneak preview:
[
53AEFBC2-832F-459E-BB29-7DB69489AC7F
](url)

Work in progress for All_Trips & Charging_Profile. 
@gerard33  @rikroe When i’m done, should i do a PR to HA core or do i have to wait until the new bimmer_connected has been bumped to a newer version?

**Comment by rikroe** [comment]
Thats looking great, many thanks!

Please create a PR to HA when your done, just two thing to keep in mind: 
- We have to publish a new release of the library before (so no beta release in manifest.json) and I would like to clean some little things up - hope I have the chance this week.
- Probably you have to wait until the config flow PR is merged into HA - this should be done latest with 0.118 so you do not have that many changes.

**Comment by gerard33** [comment]
Great work @EddyK69 
I have made a new issue #224 to continue the discussion and next steps 😄

**Pull request merged**
