### PR TITLE
CLI: Set observer position only for vehicle finder

### LINKED ISSUE #644: CLI requires lat/lon in params for charging
@rikroe I ran into a problem with 16.1 CLI version, when trying to start/stop charging:

`bimmerconnected charge USERNAME PASSWORD rest_of_world VIN start`

`Traceback (most recent call last):
  File "C:\Users\jeter\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jeter\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jeter\AppData\Local\Programs\Python\Python310\Scripts\bimmerconnected.exe\__main__.py", line 7, in <module>
  File "C:\Users\jeter\AppData\Local\Programs\Python\Python310\lib\site-packages\bimmer_connected\cli.py", line 334, in main
    if args.lat and args.lng:
AttributeError: 'Namespace' object has no attribute 'lat'`

I guess you need something like: 
`if args.lat.exists()` in line 334 in cli.py?

_Originally posted by @jeterke in https://github.com/bimmerconnected/bimmer_connected/discussions/627#discussioncomment-10214331_

Issue after refactoring CLI. Testing/parsing `lat` and `lon` only needs to be done for specific parameters.

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

Set observer position from positional arguments only for vehicle finder.

## Type of change
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #644 
- This PR is related to issue: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by rikroe** [comment]
@jeterke could you try this out just from the code change? Cannot test it, don't have an EV.

**Comment by jeterke** [comment]
Tested. Charging start/stop now works fine. Great news!

However, I also tested vehiclefinder and discovered that there is a problem. See below. 
Not an issue for me since I don't use it. 

DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-list "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-data/profile "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-list "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-list "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.vehicle:Getting vehicle list
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1722932370640 "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-crccs/v2/vehicles?fields=charging-profile&has_charging_settings_capabilities=true "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v4/presentation/remote-commands/vehicle-finder "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '9fdd4153-e2bb-4322-acd3-637abc970739'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=9fdd4153-e2bb-4322-acd3-637abc970739 "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '9fdd4153-e2bb-4322-acd3-637abc970739' is: EXECUTED
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v4/presentation/remote-commands/eventPosition?eventId=9fdd4153-e2bb-4322-acd3-637abc970739 "HTTP/1.1 400 Bad Request"
ERROR:bimmer_connected.api.client:MyBMWAPIError due to HTTPStatusError: Bad Request -
MyBMWAPIError: HTTPStatusError: Bad Request -

Switched back to version 0.16.1 and vehiclefinder works fine in that version:
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-list "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-data/profile "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-list "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vcs/v5/vehicle-list "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.vehicle:Getting vehicle list
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v4/vehicles/state?apptimezone=0&appDateTime=1722932567959 "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-crccs/v2/vehicles?fields=charging-profile&has_charging_settings_capabilities=true "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v4/presentation/remote-commands/vehicle-finder "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '1f42e9af-4db4-48a8-9009-62e0b357287a'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=1f42e9af-4db4-48a8-9009-62e0b357287a "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '1f42e9af-4db4-48a8-9009-62e0b357287a' is: PENDING
DEBUG:bimmer_connected.vehicle.remote_services:getting remote service status for '1f42e9af-4db4-48a8-9009-62e0b357287a'
DEBUG:httpx._client:HTTP Request: POST https://cocoapi.bmwgroup.com/eadrax-vrccs/v3/presentation/remote-commands/eventStatus?eventId=1f42e9af-4db4-48a8-9009-62e0b357287a "HTTP/1.1 200 OK"
DEBUG:bimmer_connected.vehicle.remote_services:current state of '1f42e9af-4db4-48a8-9009-62e0b357287a' is: EXECUTED
ERROR:bimmer_connected.vehicle.location:Error retrieving vehicle position. Unknown position: Set observer position to retrieve vehicle coordinates!
ExecutionState.EXECUTED
{'gps_position': GPSPosition(latitude=5x.xxxxxxxxxxxxxxxxxx, longitude=4.xxxxxxxxxxxxxxxxxx), 'heading': xxx}

**Comment by rikroe** [comment]
Thanks for testing, this should not fail. I'll have another look!

**Comment by rikroe** [comment]
Just tried it out myself - did you add the `lat` and `lon` parameters? They may be required for the new endpoint added with [0.16.0](https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.16.0) and I see in your working example that the request is against `v3` instead of `v4`.

**Pull request merged**
