### PR TITLE
Add climatization status

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

This PR adds (if available on vehicle):
  - climatization status (`HEATING`, `COOLING`, `STANDBY`, `INACTIVE`, `UNKNOWN`)
  - end time of climatization
  - True/False indicator if climatization is ON

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: #521 

## Checklist

- [x] The code change is tested and works locally.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Review by gerard33 — APPROVED** [review]

**Comment by mannibis** [comment]
Will this now make the Climate function 1 button (like the lock), instead of having a start and stop switch? By knowing the status of climatization we can now have a true climate entity that will stay on while until the status changes, allowing for a start/stop single function.

**Comment by rikroe** [comment]
> Will this now make the Climate function 1 button (like the lock)

Yes, this is the plan. At least for cars that return the climate state. 
For others, we'll stay with the only one-shot buttons. 

However the PR for HA is not yet open, so might take a little bit.

**Comment by mannibis** [comment]
So not sure it's me not doing something right but I don't see any new entities in the HA integration. Is the integration upgrade process automatic when updating HA? I'm on the 2023.5 release but it doesn't seem like the BMW integration is any different

**Comment by rikroe** [comment]
Thanks for the reminder - open quite a lot of PRs to HA so forgot to actually add one climate status. 

Maybe I'll find some time next week to implement it. I'll update in the discussion.

**Pull request merged**
