### PR TITLE
Fix remote services in rest_of_world and north_america

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

Merge Fix remote services in rest_of_world (#310)

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by rikroe** [comment]
@gerard33, @pzim-devdata could you both please test against `dev` if remote services are working fully for you?
@heyepic, @dazole could you guys please test if remote execution in north america works as well? Can't test it by myself, as I don't have any cars in my account there ;)

**Comment by dazole** [comment]
I was able successfully test status, light flash, fingerprint vehicle finder and send message. "vehicle finder" only returned "success", though, and not any kind of lat/lon or anything else.  I'm not sure if that's expected or not.

I don't use HA, though, so I wasn't able to test door lock or ventilation.

**Comment by rikroe** [comment]
> I was able successfully test status, light flash, fingerprint vehicle finder and send message. "vehicle finder" only returned "success", though, and not any kind of lat/lon or anything else. I'm not sure if that's expected or not.

Thanks, that's great to hear! `vehicle_finder` doesn't give a result, but the timestamp in status will be updated.

**Review by gerard33 — APPROVED** [review]

**Comment by pzim-devdata** [comment]
After upgrading to 7.19, it works perfectly. Thank you ! ;-)

**Pull request merged**
