### PR TITLE
Changed the auth method 

### PR DESCRIPTION
**Pull request by Markinus**
This is supporting the navigation and efficiency services again.

## Proposed change

New auth method. See here:
https://github.com/bimmerconnected/bimmer_connected/issues/158

## Type of change
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

It is testen in europe only. I don't know if this auth is working in china/america too.

- This PR is related to issue: #158 

## Checklist

- [X] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by Markinus** [comment]
@rikroe I prepared it but it fails on the test. I have no Idea why. I think it would be better if you could take a look to it.

**Comment by rikroe** [comment]
Thanks!

I thought I answered on the issue, but appentrently I just typed without saving, sorry.

I am not sure if it makes sense to use the other Auth endpoint. If I have the full picture then this is a legacy endpoint used by the CD web interface and not used by the app (which has much more functionality).
The last issue with login came because BMW decided to turn off the old authentication for the app APIs.

However I understand that you want to get these values.

Maybe it makes sense to split the login into the main one and this one (legacy) and then try to use them interchangeable depending on the endpoint.

I will definitely have a look at this, however cannot promise it this week.

**Comment by Markinus** [comment]
Yes, maybe is this the best way, to use both methodes.
Thanks.

**Comment by andig** [comment]
I'm using this method in evcc. Advantage is less requests, i.e. no need to exchange code for token but obtain token directly. Also seems that the old tokens still work with the new mybmw api endpoints.

**Comment by rikroe** [comment]
> I'm using this method in evcc. Advantage is less requests, i.e. no need to exchange code for token but obtain token directly. Also seems that the old tokens still work with the new mybmw api endpoints.

Oh, this is very interesting, thanks! tested it for rest_of_world and north_america and still works. 
Unfortunately doesn't help our issues with china - the endpoint exists but I cannot find the correct `client_id` required :/

**Comment by rikroe** [comment]
Closed as we have migrated to the MyBMW API. 

Many thanks anyways!

**Pull request closed without merging**
