### PR TITLE
Update of charging sessions and statistics URLs to v2

### PR DESCRIPTION
**Pull request by Gr3yh0und**
## Proposed change
The charging statistics and charging sessions URLs have changed in April 2024. Although they are not yet used in this project, this is probably helpful for other projects to be aware of.

## Type of change
- [x] Bugfix (non-breaking change as this Consts aren't used yet)

## Checklist

- [x] The code change is tested and works locally.

### CODE REVIEW

**Comment by rikroe** [comment]
Thanks! I've also seen that some other endpoints have been updated, but haven't had the chance to go through everything. This PR is a good reminder to do that though.

**Comment by Gr3yh0und** [comment]
No worries. I was just playing around with it and started building my own Python scripts to collect data and forward it to my TIG stack while I was coming along the statistics stuff and saw, that also other integrations of openHAB, HA, ioBroker and so on always seem to reference here as well. So probably tackling it in the point of truth might help also the other maintainers.

Are there any plans on having a look into the sessions/statistics from your side on the roadmap or should I maybe give it a try?

**Comment by rikroe** [comment]
I don't have an EV, so don't need it personally and cannot test it.

There was #569 which implemented a lot but then it got stale. I would still prefer this as a type of remote service (https://github.com/bimmerconnected/bimmer_connected/pull/569#issuecomment-1902630313) as we don't need to get this every 5 minutes with the rest of the state.

So yeah, if you want to look at it, sure!

**Review by rikroe — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
