### PR TITLE
Add headunit data class also exposing current vehicle software version

### PR DESCRIPTION
**Pull request by cubinet-code**
## Proposed change
This enhancement adds headunit information like ID Drive generation and its current software revision.
Only vehicle data that also exists on older vehicles was used.

```Headunit(idrive_version='ID8', headunit_type='MGU', software_version='07/2023.35')```

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist
- [x] The code change is tested and works locally.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by rikroe** [comment]
Need to double check, there seems to be something wrong with all pytests (maybe a test dependency upgrade, not your code l.

**Comment by cubinet-code** [comment]
Thanks for having a look. 

It seem to be related to this: https://github.com/adamchainz/time-machine/issues/387 in test_get_remote_position_too_old.

```
diff --git a/requirements-test.txt b/requirements-test.txt
-time_machine
+time_machine==2.12.0
```

After going back to 2.12.0 version tests pass again:
```
============================================================================ test session starts ============================================================================
platform darwin -- Python 3.11.3, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/oliverf/Documents/Project/bimmer_connected
configfile: pyproject.toml
plugins: anyio-4.0.0, respx-0.20.2, timeout-2.1.0, cov-4.1.0, asyncio-0.21.1, time-machine-2.12.0
asyncio: mode=Mode.STRICT
collected 85 items                                                                                                                                                          

bimmer_connected/tests/test_account.py ..........................                                                                                                     [ 30%]
bimmer_connected/tests/test_api.py .....                                                                                                                              [ 36%]
bimmer_connected/tests/test_remote_services.py ................                                                                                                       [ 55%]
bimmer_connected/tests/test_utils.py .....                                                                                                                            [ 61%]
bimmer_connected/tests/test_vehicle.py ............                                                                                                                   [ 75%]
bimmer_connected/tests/test_vehicle_status.py .....................                                                                                                   [100%]

============================================================================ 85 passed in 8.20s =============================================================================

**Comment by rikroe** [comment]
Thanks for the hint! In that case, I would be fine with pinning `time_machine<2.13.0` for now.

**Comment by cubinet-code** [comment]
I submitted a PR, so you don't have to :)

**Comment by rikroe** [comment]
> I submitted a PR, so you don't have to :)

Thanks, please rebase and this should be good to go.

**Review by rikroe — APPROVED** [review]
LGTM, many thanks!

**Pull request merged**
