### PR TITLE
Add bmw-unit-preferences

### LINKED ISSUE #450: Distances in miles instead of km
I just upgraded to the latest verion of the library and now all my data comes back with mi instead of km in the units. How can I change it back to km?

_Originally posted by @th0mi in https://github.com/bimmerconnected/bimmer_connected/discussions/448_

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

Apparently, one has to give unit preferences when making API calls now.

- https://github.com/evcc-io/evcc/issues/3526
- #448

It is possible to change between metric/imperial units by:
- initializing `MyBMWAccount(..., use_metric_units=False)`
- calling `account.set_use_metric_units(False)` after init.

## Type of change
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #450 
- This PR is related to issue: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by FlyingDiver** [comment]
Shouldn't that be a named parameter to the function so that it can be easily overridden instead of having to specify the entire header dict?

**Comment by rikroe** [comment]
It could be written as a named parameter, yes. The question however would be how to control the calls, as this function is called in the backend.

I could image that it makes sense to add `unit` properties to [`MyBMWClientConfiguration`](https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/api/client.py#L17) as we cannot really distinguish based on the region.

If the library is used from Home Assistant, we could use use the HA settings, and if used somewhere else it is at least configurable (through passing `MyBMWClientConfiguraition` or a setter method on `MyBMWAccount`).

Any thoughts?

Also, as you're based in NA if I remember correctly - could you please check how the values behave for you? Apparently in ROW, the odometer shows the value in `mi` but returns the unit as `km`.

**Comment by FlyingDiver** [comment]
I was hoping it could be something passed through the MyBMWAccount constructor, as that's the primary entry point for the API.  Or set as an attribute after creation.

I don't understand the results I get now.  I get mileage in mi, but fuel volume in liters.  ???

**Comment by rikroe** [comment]
> I was hoping it could be something passed through the MyBMWAccount constructor, as that's the primary entry point for the API. Or set as an attribute after creation.

That should be possible, will have a look tomorrow. 

> I don't understand the results I get now. I get mileage in mi, but fuel volume in liters. ???

I don't know what the API expects or responds in this case. 
Could you try multiple values, to figure out what exactly we have to send for metric/imperial units?

**Comment by FlyingDiver** [comment]
Honestly, I'm not sure I have a way to set that value now.  Unless I edit the code installed in site_packages.  Unfortunately, my setup can't use a venv.

**Comment by rikroe** [comment]
If your setup does not reload the package from pypizon restart, editing the files in site_packages would be a viable, albeit hacky solution.

**Comment by rikroe** [comment]
Just figured out that I am able to change the unit preferences in the MyBMW app.

With a little bit of refactoring, it is now possible to either change units by 
- initializing `MyBMWAccount(..., use_metric_units=False)
- calling `account.set_use_metric_units(False)` after init.

**Comment by sincze** [comment]
> Just figured out that I am able to change the unit preferences in the MyBMW app.

As that seems to be correct my MyBMW app is set for Liters and KM in the UNITS section, however still shows the tyre pressure in the APP in PSI instead of Bar, I think they still have some work to do at BMW.

**Review by gerard33 — APPROVED** [review]

**Pull request merged**
