### PR TITLE
Remove support for Python 3.7

### PR DESCRIPTION
**Pull request by rikroe**
## Breaking change

Support for Python 3.7 is removed. As we now support Python 3.12, this library requires Python >= 3.8.

## Proposed change

Remove Python 3.7 support due to offical end of life.

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: #553 

## Checklist

- [x] The code change is tested and works locally.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by rikroe** [comment]
@cdce8p can't request a review from you directly but would like to have you opinion if I missed something. Thanks!

**Review by cdce8p — CHANGES_REQUESTED** [review]
A few more
https://github.com/bimmerconnected/bimmer_connected/blob/b036c2520f69c0188ea16f7f109cac48f4c394d9/.readthedocs.yml#L13
https://github.com/bimmerconnected/bimmer_connected/blob/b036c2520f69c0188ea16f7f109cac48f4c394d9/README.rst?plain=1#L26

https://github.com/bimmerconnected/bimmer_connected/blob/b036c2520f69c0188ea16f7f109cac48f4c394d9/bimmer_connected/tests/common.py#L13-L20
The last one is used in other test modules as well.

**Comment by rikroe** [comment]
Thanks! Didn't think on using the search 😨

**Review by gerard33 — APPROVED** [review]

**Review by cdce8p — APPROVED** [review]
LGTM

**Pull request merged**
