### PR TITLE
Add charging sessions and charging statistics data for hybrids and BEVs

### PR DESCRIPTION
**Pull request by cubinet-code**
## Proposed change
This enhancement adds charging statistics and charging session information provided by the connected drive API for hybrid and BEVs.

- Collects the current months data only, as to reduce the risk to run into rate limiting of the API servers
- To keep code consistent, it has been implemented matching the logic that was used for "charging_settings".
- Additional tests and test live-data from a U11 have been added to support the change
  - test_charging_type_unknown
  - test_charging_sessions and charging blocks
  - test_charging_statistics
  - test_charging_type_unknown
 - Prepared to expose software_version, total_energy_charged, charging_session_count to homeassistant component
 
## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information
A preliminary review would be appreciated to understand if my PR meets the project requirements.
Unfortunately I do not have an ICE vehicle available in my account. While the tests with the existing vehicle data passes just fine, it would be very interesting to run the fingerprint against an ICE vehicle to understand the API results if no charging information is available.

- This PR is partly addressing feature request #402

## Checklist
- [x] The code change is tested and works locally.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by rikroe** [comment]
Need to have a look in more detail later - maybe I get the change on the weekend.

Two things came to my mind when looking at the changed files:
- Did you create the JSON files through the fingerprint function? If so, we should make sure that e.g. `address` is [anonymized](https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/api/utils.py#L87) correctly.
- Also our internal [request queue for debugging](https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/api/client.py#L18) should be increased, if we get alone 8 requests for the statistics

**Comment by cubinet-code** [comment]
Thanks for the hints!

I updated the anonymisation dict to remove additonal charging related private data.

Also, increased response queue depth to 45 with the following rational:

- 4 * base vehicle data
- 1 * charging statistic
- 40 * possible monthly charging sessions, should not be more than 1 per day)

**Comment by rikroe** [comment]
Hi, I'm sorry to leave you hanging for that long. Other priorities...

I thought about your changes and think that we should not request all those endpoints everytime a normal refresh is done (i.e. every 5 minutes as default for Home Assistant). We've had rate limiting issues in the past and I dont want to increase the load to BMW servers too much if possible.

How do you feel about a solution similar to a remote service? I.e. you have to manually request the historic data, like triggering the vehiclefinder service.

The result could be either stored in a full blown object (like you have already implemented) or even just returned as plain JSON - depending on how you want to continue working with the data.

**Comment by fideias** [comment]
Will this feature be reviewed and added in short term ?

**Pull request closed without merging**
